-- Supabase Schema for Gym Supplements eCommerce (PostgreSQL)

-- 1. Create the `products` table (If you haven't run this via the SQL Editor manually)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  rating numeric default 0,
  image text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Configure Row Level Security (RLS)
alter table public.products enable row level security;

-- Policy 1: Allows anyone (anonymous users and authenticated users) to read products
-- Your frontend ONLY needs to read this data.
create policy "Allow public read access to products"
  on public.products
  for select
  to public
  using ( true );

-- Note: The seeding script bypasses this RLS policy entirely by using the `service_role_key`. 
-- Do not create an INSERT policy unless your users can add products via the React app!
